import type { Category, Video } from '@/lib/types';
import { PlaceHolderImages } from '@/lib/placeholder-images';

export const categories: Category[] = [
  { id: '1', name: 'Komedi', emoji: '😂', color: 'bg-yellow-500' },
  { id: '2', name: 'Tarif', emoji: '🍕', color: 'bg-orange-500' },
  { id: '3', name: 'Spor', emoji: '💪', color: 'bg-blue-500' },
  { id: '4', name: 'Motivasyon', emoji: '💡', color: 'bg-purple-500' },
  { id: '5', name: 'Eğitim', emoji: '📚', color: 'bg-green-500' },
  { id: '6', name: 'Seyahat', emoji: '✈️', color: 'bg-teal-500' },
];

export const videos: Video[] = [
  {
    id: '1',
    title: 'Lezzetli Makarna Tarifi',
    thumbnailUrl: PlaceHolderImages[0].imageUrl,
    imageHint: PlaceHolderImages[0].imageHint,
    platform: 'instagram',
    duration: '2:34',
    category: categories[1],
    notes: 'Parmesan ekle, tuz az olsun. Mükemmel bir akşam yemeği için harika bir seçim.',
    isFavorite: true,
    dateAdded: '3 gün önce',
    originalUrl: '#',
  },
  {
    id: '2',
    title: 'En Komik Kedi Videoları',
    thumbnailUrl: PlaceHolderImages[1].imageUrl,
    imageHint: PlaceHolderImages[1].imageHint,
    platform: 'tiktok',
    duration: '0:45',
    category: categories[0],
    isFavorite: false,
    dateAdded: '1 hafta önce',
    originalUrl: '#',
  },
  {
    id: '3',
    title: 'Evde 10 Dakikada Kardiyo',
    thumbnailUrl: PlaceHolderImages[2].imageUrl,
    imageHint: PlaceHolderImages[2].imageHint,
    platform: 'youtube',
    duration: '10:12',
    category: categories[2],
    isFavorite: true,
    dateAdded: '2 gün önce',
    originalUrl: '#',
  },
  {
    id: '4',
    title: 'Güne Başlarken Motivasyon Konuşması',
    thumbnailUrl: PlaceHolderImages[3].imageUrl,
    imageHint: PlaceHolderImages[3].imageHint,
    platform: 'tiktok',
    duration: '1:00',
    category: categories[3],
    isFavorite: false,
    dateAdded: '5 gün önce',
    originalUrl: '#',
  },
  {
    id: '5',
    title: 'JavaScript ES6 Özellikleri',
    thumbnailUrl: PlaceHolderImages[4].imageUrl,
    imageHint: PlaceHolderImages[4].imageHint,
    platform: 'youtube',
    duration: '15:45',
    category: categories[4],
    notes: 'Arrow functions ve destructuring konularını tekrar et.',
    isFavorite: true,
    dateAdded: '1 ay önce',
    originalUrl: '#',
  },
  {
    id: '6',
    title: 'Bali\'de Gezilecek Yerler',
    thumbnailUrl: PlaceHolderImages[5].imageUrl,
    imageHint: PlaceHolderImages[5].imageHint,
    platform: 'instagram',
    duration: '0:58',
    category: categories[5],
    isFavorite: false,
    dateAdded: '2 hafta önce',
    originalUrl: '#',
  },
  {
    id: '7',
    title: 'Stand-up Şov Kesitleri',
    thumbnailUrl: PlaceHolderImages[6].imageUrl,
    imageHint: PlaceHolderImages[6].imageHint,
    platform: 'tiktok',
    duration: '0:30',
    category: categories[0],
    isFavorite: false,
    dateAdded: '4 gün önce',
    originalUrl: '#',
  },
  {
    id: '8',
    title: 'Sağlıklı Smoothie Bowl',
    thumbnailUrl: PlaceHolderImages[7].imageUrl,
    imageHint: PlaceHolderImages[7].imageHint,
    platform: 'instagram',
    duration: '1:15',
    category: categories[1],
    isFavorite: true,
    dateAdded: '6 gün önce',
    originalUrl: '#',
  },
   {
    id: '9',
    title: 'Sabah Egzersiz Rutini',
    thumbnailUrl: PlaceHolderImages[8].imageUrl,
    imageHint: PlaceHolderImages[8].imageHint,
    platform: 'youtube',
    duration: '8:20',
    category: categories[2],
    notes: 'Bu rutini her sabah yapmaya çalış.',
    isFavorite: false,
    dateAdded: '10 gün önce',
    originalUrl: '#',
  },
  {
    id: '10',
    title: 'İtalya Sokak Lezzetleri',
    thumbnailUrl: PlaceHolderImages[9].imageUrl,
    imageHint: PlaceHolderImages[9].imageHint,
    platform: 'tiktok',
    duration: '0:55',
    category: categories[5],
    isFavorite: true,
    dateAdded: '3 hafta önce',
    originalUrl: '#',
  }
];
